version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Etc/UTC"

    open-pull-requests-limit: 1

    labels:
      - "dependencies"

    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
