version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 1
    assignees:
      - "daniftodi"
    labels:
      - "dependencies"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
